/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import com.dao.BreedDTO;

/**
 *
 * @author DUC PHU
 */
public class BreedItem extends javax.swing.JPanel {

    /**
     * Creates new form BreedItem
     */
    String flag;
    BreedDTO breedTemp;
    PetOnStoreDetail petForm;
    AddPetForm addForm;
    BreedChooser breedChose;
    public BreedItem(BreedDTO breedTemp, PetOnStoreDetail petForm, BreedChooser breedChose, String flag) {
        this.flag = flag;
        this.petForm = petForm;
        this.breedTemp = breedTemp;
        this.breedChose = breedChose;
        initComponents();
        setSize(520, 36);
        svgAdd.setSVGImage("com/image/add.svg", 36, 36);
    }
    
    public BreedItem(BreedDTO breedTemp, AddPetForm addForm, BreedChooser breedChose, String flag) {
        this.flag = flag;
        this.addForm = addForm;
        this.breedTemp = breedTemp;
        this.breedChose = breedChose;
        initComponents();
        setSize(520, 36);
        svgAdd.setSVGImage("com/image/add.svg", 36, 36);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svgAdd = new com.gui.SvgImage();
        lbBreedName = new javax.swing.JLabel();

        svgAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgAddMouseClicked(evt);
            }
        });

        lbBreedName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbBreedName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBreedName, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(svgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBreedName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(svgAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbBreedName.setText(""+breedTemp.getName());
    }// </editor-fold>//GEN-END:initComponents

    private void svgAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAddMouseClicked
        // TODO add your handling code here:
        if(flag.equals("edit"))
        {
            petForm.setBreed(breedTemp.getName()+"");    
        }
        else if(flag.equals("add"))
        {
            addForm.setBreed(breedTemp.getName()+"");
        }
        breedChose.dispose();
    }//GEN-LAST:event_svgAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBreedName;
    private com.gui.SvgImage svgAdd;
    // End of variables declaration//GEN-END:variables
}
