/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import com.bus.ImportBUS;
import com.bus.ImportDetailBUS;
import com.dao.ImportDAO;
import com.dao.ImportDTO;
import com.dao.ImportDetailDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author minht
 */
public class ImportGUI extends javax.swing.JPanel {
        private ArrayList<ImportDTO> impList = new ArrayList<>();
        private ArrayList<ImportDetailDTO> impDetList = new ArrayList<>();
    /**
     * Creates new form ImportGUI
     */
    public ImportGUI() throws SQLException {
        initComponents();
        
        btnAdd.setSVGImage("com/image/add.svg", 40, 40);
        btnRefresh.setSVGImage("com/image/reload.svg", 40, 40);
        btnSearch.setSVGImage("com/image/search.svg", 40, 40);
        
        ImportBUS impBUS = new ImportBUS();
        impList =impBUS.getList();
         addRowtoImportTable(impList);

    }

    public void addRowtoImportTable(ArrayList<ImportDTO> impList) throws SQLException{
        DefaultTableModel model = (DefaultTableModel) tblImport.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[4];
        for (int i = 0; i < impList.size(); i++) {
            rowData[0] = impList.get(i).getImportID();
            rowData[1] = impList.get(i).getCreatedDate();
            rowData[2] = impList.get(i).getTotalAmount();
            rowData[3] = impList.get(i).getEmployeeID();
            model.addRow(rowData);
        }
    }
        public void addRowtoDetailTable(String impID) throws SQLException{
        ImportDetailBUS impDetBUS = new ImportDetailBUS();
        ArrayList<ImportDetailDTO> allDetList =impDetBUS.getList();
        ArrayList<ImportDetailDTO> tempDetList =new ArrayList<>();
        
        for (int i = 0; i < allDetList.size(); i++) {
            if(allDetList.get(i).getImportID().equals(impID))
                tempDetList.add(allDetList.get(i));
        }
        impDetList=tempDetList;
        
        DefaultTableModel model = (DefaultTableModel) tblImportDetail.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[7];
        for (int i = 0; i < impDetList.size(); i++) {
            rowData[0] = impDetList.get(i).getImportID();
            rowData[1] = impDetList.get(i).getProductID();
            rowData[2] = impDetList.get(i).getProductName();
            rowData[3] = impDetList.get(i).getQuantity();
            rowData[4] = impDetList.get(i).getImportPrice();
            rowData[5] = impDetList.get(i).getSoldPrice();
            rowData[6] = impDetList.get(i).getAmount();
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBody = new javax.swing.JPanel();
        pnToolBar = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new com.gui.SvgImage();
        btnRefresh = new com.gui.SvgImage();
        btnAdd = new com.gui.SvgImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImport = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblImportDetail = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHeader.setBackground(new java.awt.Color(240, 81, 25));
        pnHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHẬP HÀNG");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setFocusable(false);
        pnHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 400, 100));

        add(pnHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        pnBody.setBackground(new java.awt.Color(240, 81, 25));
        pnBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnToolBar.setBackground(new java.awt.Color(240, 81, 25));
        pnToolBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnToolBar.add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 1000, 40));

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        pnToolBar.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 40, 40));

        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        pnToolBar.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 40, 40));

        btnAdd.setText("Add");
        pnToolBar.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 40, 40));

        pnBody.add(pnToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 51));

        tblImport.setBackground(new java.awt.Color(255, 102, 51));
        tblImport.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ngày tạo", "Tổng tiền", "Mã nhân viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblImportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblImport);
        if (tblImport.getColumnModel().getColumnCount() > 0) {
            tblImport.getColumnModel().getColumn(0).setResizable(false);
            tblImport.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblImport.getColumnModel().getColumn(1).setResizable(false);
            tblImport.getColumnModel().getColumn(2).setResizable(false);
            tblImport.getColumnModel().getColumn(3).setResizable(false);
        }

        pnBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 435));

        jScrollPane2.setBackground(new java.awt.Color(255, 102, 51));

        tblImportDetail.setBackground(new java.awt.Color(255, 102, 51));
        tblImportDetail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblImportDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblImportDetail);
        if (tblImportDetail.getColumnModel().getColumnCount() > 0) {
            tblImportDetail.getColumnModel().getColumn(0).setResizable(false);
            tblImportDetail.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblImportDetail.getColumnModel().getColumn(1).setResizable(false);
            tblImportDetail.getColumnModel().getColumn(2).setResizable(false);
            tblImportDetail.getColumnModel().getColumn(3).setResizable(false);
            tblImportDetail.getColumnModel().getColumn(4).setResizable(false);
            tblImportDetail.getColumnModel().getColumn(5).setResizable(false);
            tblImportDetail.getColumnModel().getColumn(6).setResizable(false);
        }

        pnBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 820, 435));

        add(pnBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1280, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void tblImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImportMouseClicked
        // TODO add your handling code here:
        int i=tblImport.getSelectedRow();
        try {
            addRowtoDetailTable((String) tblImport.getModel().getValueAt(i, 0));
        } catch (SQLException ex) {
            Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblImportMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        ArrayList<ImportDTO> filter =new ArrayList<>();
        
        //ArrayList<ImportDTO> filterEmployeeID =new ArrayList<>();
        String search = tfSearch.getText();
        System.out.println("Txt: "+search+" Type: "+search.getClass().getName());
        if(search.length()!=0){
            filter.clear();
            for(int i=0;i<impList.size();i++){
                if(impList.get(i).getImportID().contains(search)
                        || impList.get(i).getEmployeeID().contains(search)
                        || impList.get(i).getCreatedDate().contains(search)
                        || search.equals(""+impList.get(i).getTotalAmount())
                        ){
                    boolean isExist=false;
                    for(int j=0;j<filter.size();j++){
                        if(impList.get(i).getImportID().equals(filter.get(j).getImportID())) isExist=true;
                    }
                    if(!isExist)
                    filter.add(impList.get(i));
                }
                
            }

        //}
         try {
                addRowtoImportTable(filter);
            } catch (SQLException ex) {
                Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
            try {
                // TODO add your handling code here:
                addRowtoImportTable(impList);
            } catch (SQLException ex) {
                Logger.getLogger(ImportGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnRefreshMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gui.SvgImage btnAdd;
    private com.gui.SvgImage btnRefresh;
    private com.gui.SvgImage btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnToolBar;
    private javax.swing.JTable tblImport;
    private javax.swing.JTable tblImportDetail;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
