/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import com.dao.PetOnStoreDTO;
import com.dao.PetProductDTO;
import com.dao.SoldPetDTO;
import com.dao.ProductDTO;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author DUC PHU
 */
public class ProductCom extends javax.swing.JPanel {

    /**
     * Creates new form ProductCom
     */
    ProductUI ui;
    ProductDTO product;
    Validator valid = new Validator();
    public ProductCom(ProductDTO product, ProductUI ui) {
        this.product = product;
        this.ui = ui;
        initComponents();
        setSize(new Dimension(345, 265));
        svgEdit.setSVGImage("com/image/edit.svg", 48, 48);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImage = new javax.swing.JLabel();
        lbSoldPrice = new javax.swing.JLabel();
        lbNameID = new javax.swing.JLabel();
        svgEdit = new com.gui.SvgImage();

        setBackground(new java.awt.Color(255, 255, 255));

        lbImage.setBackground(new java.awt.Color(204, 204, 255));
        lbImage.setOpaque(true);

        lbSoldPrice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSoldPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbNameID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNameID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        svgEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNameID, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbSoldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(svgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNameID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSoldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(svgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setImage();
        String price = valid.formatMoney(product.getSoldPrice());
        lbSoldPrice.setText(""+price);
        lbNameID.setText(""+product.getName()+ " "+product.getId());
    }// </editor-fold>//GEN-END:initComponents

    private void svgEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgEditMouseClicked
        // TODO add your handling code here:
        if(product instanceof PetOnStoreDTO)
        {
            PetOnStoreDTO petTemp = (PetOnStoreDTO) product;
            PetOnStoreDetail detailForm = new PetOnStoreDetail(petTemp, ui);
            detailForm.setVisible(true);
        }
        
    }//GEN-LAST:event_svgEditMouseClicked

    public void setImage()
    {
        if(product.getImageUrl().equals("null"))
        {
            
        }
        else{
            int labelWidth = 345;
            int labelHeight = 176;
            String imageUrl = product.getImageUrl();
            ImageIcon imageIcon = new ImageIcon("src/com/image/" + imageUrl);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
            ImageIcon newImageIcon = new ImageIcon(newImage);
            lbImage.setIcon(newImageIcon);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbNameID;
    private javax.swing.JLabel lbSoldPrice;
    private com.gui.SvgImage svgEdit;
    // End of variables declaration//GEN-END:variables
}
